[rule]
id = "file-path-organization.by-type"
name = "By Type File Organization"
description = "Organize files by type based on frontmatter, tags, or filename patterns"
category = "file-organization"

[config]
path_allowlist = ["**/*.md"]
path_denylist = ["Meta/**", "Templates/**"]
include_patterns = ["**/*"]
exclude_patterns = [".*"]

[settings]
base_directory = "Notes"
create_subdirectories = true
update_links = true
preserve_existing_structure = false
date_format = "YYYY/MM"
topic_extraction_method = "frontmatter"
max_depth = 3

[settings.type_mapping]
daily = "Daily Notes"
meeting = "Meetings"
project = "Projects"
reference = "Reference"
note = "General Notes"
idea = "Ideas"
