[rule]
id = "frontmatter-required-fields.custom"
name = "Custom Frontmatter Fields"
description = "Enforce custom set of required frontmatter fields"
category = "frontmatter"

[config]
path_allowlist = ["**/*.md"]
path_denylist = ["Meta/Templates/**", "Meta/MOCs/**"]
include_patterns = ["**/*"]
exclude_patterns = [".*", "README.md"]

[settings]
required_fields = ["title", "tags", "status"]
auto_fix = true
default_status = "draft"
date_format = "YYYY-MM-DD"
strict_arrays = true

[settings.custom_fields]
priority = "high"
project = ""
author = ""
